services:
  auth:
    container_name: auth
    build:
      dockerfile: ./app/Dockerfile
    networks:
      - gateway
      - farmer-be
      - client-be



networks:
  gateway:
    external: true
    name: g-auth
  farmer-be:
    name: a-farmer-be
  client-be:
    name: a-client-be
      