FROM nikolaik/python-nodejs
WORKDIR /usr/src/app
COPY . .

RUN pip install requests;exit 0
RUN pip install pandas; exit 0
RUN pip install numpy; exit 0
RUN pip install -U scikit-learn;exit 0
RUN npm install express;exit 0
RUN npm install request;exit 0
RUN npm install body-parser;exit 0
RUN npm install amqplib

CMD node server.js & python fakeDetector2.py
