services:
  api-gateway:
    build:
      dockerfile: ./src/Dockerfile
    ports:
      - 8080:8080
    networks:
      - client-be
      - auth
      - farmer-be
      - image
      - order-be


networks:
  auth:
    name: g-auth
  client-be:
    name: g-client-be
  farmer-be:
    name: g-farmer-be
  order-be:
    name: g-order-be  
  image:
    name: g-images
