version: '3.1'

services:

  mysql-order:
    image: mysql:8.0.34
    container_name: mysql-order   
    volumes:
      - order-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Order
    networks:
        - internal

  order-be:
    container_name: order-be
    build:
      dockerfile: ./Dockerfile
      args:
        APP_NAME: nffh-order-BE
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/Order
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-order
    networks:
      - gateway
      - internal

networks:
  gateway:
    external: true
    name: g-order-be
  internal:
    external: false


volumes:
  order-mysql-data:
      