FROM node
WORKDIR /usr/src/app
COPY . .

RUN npm install express
RUN npm install fs
RUN npm install body-parser
RUN npm install request
RUN npm install express-session
RUN npm install mysql
RUN npm install sync-mysql
RUN npm install amqplib

CMD node server.js & node getNews.js
