version: '2'
services:

  amqp:
    image: rabbitmq
    container_name: amqp-broker
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    restart: always

  eco:
    image: ivangiacomoni/eco_project_1:ecoserver
    container_name: eco-server
    ports:
      - "8081:8081"
    networks:
      static-network:
        ipv4_address: 172.20.128.1
    restart: always

  mongo:
    image: mongo
    container_name: mongo-db
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    restart: always
  
  ecothreshold:
    image: ivangiacomoni/eco_project_1:ecothreshold
    container_name: eco-threshold
    networks:
      static-network:
        ipv4_address: 172.20.128.4
    restart: always

  ecoapp:
    image: ivangiacomoni/eco_project_1:ecoapp
    container_name: eco-app
    ports:
      - "8080:8080"
    networks:
      static-network:
        ipv4_address: 172.20.128.5
    restart: always


      

    
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24