version: '3.1'
services:

  db:
    image: mysql
    container_name: "db"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - volume:/mysql

  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - volume:/adminer

  backend:
    container_name: "backend"
    image: bbooss97/backend:latest
    ports:
      - 3001:3001
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    volumes:
      - volume:/backend

  fakedetector:
    container_name: "fakedetector"
    image: bbooss97/fakedetector:latest
    ports:
      - 3000:3000
    depends_on:
      - db
      - rabbitmq
    restart: on-failure
    volumes:
      - volume:/fakedetector

  stockpredictor:
    image: bbooss97/stockpredictorimage:latest
    container_name: "stockpredictor"
    restart: on-failure
    depends_on: 
      - db
    ports:
      - 5000:5000
    volumes:
      - volume:/stockpredictor

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
      - volume:/rabbitmq

volumes:
  volume:

